routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('test', function(){
	\Artisan::call('help');
	return 'hello world';
});

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home']);

Route::group(['prefix' => 'community'], function(){
	Route::resource('topic', 'TopicController');
	Route::resource('post', 'PostController');

	Route::post('topic/{topic}', ['uses' => 'TopicController@reply', 'as'=>'community.topic.reply']);
	Route::post('topic/{topic}', ['uses' => 'TopicController@bump', 'as'=>'community.topic.bump']);

	Route::get('/', 'TopicController@index');



});

Route::get('verify/email/{code}', ['as' => 'email.confirm', 'uses' => 'EmailController@confirm']);


Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function(){
	Route::get('alternate', ['uses' => 'LoginController@getAlternate']);
	Route::post('alternate', ['uses' => 'LoginController@postAlternate']);

	Route::get('2fa/setup', ['uses'=>'TwoStepController@setup']);
	Route::post('2fa/setup', ['uses'=>'TwoStepController@checkSetup']);
	Route::get('2fa', ['uses'=>'TwoStepController@show']);
	Route::post('2fa', ['uses'=>'TwoStepController@check']);

	Route::get('magic/{user?}', ['as' => 'auth.magic.send', 'uses' => 'LoginController@sendMagicLink']);
	Route::get('magic/{user}/{code}', ['as' => 'auth.magic.check', 'uses' => 'LoginController@checkMagicLink']);

	Route::get('oauth', function(){
		return view('auth.oauth');
	})->middleware('auth');
});

Route::resource('user', 'UserController');
Route::get('profile', function(){
	return redirect()->route('user.show', Auth::user()->slug());
})->middleware('auth');

resources/views/layouts/partials/alerts.blade.php
@if(Session::has('info'))
	<div class="alert alert-info alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{{@Session::get('info')}}
	</div>
@endif

@if(Session::has('error'))
	<div class="alert alert-warning alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{{@Session::get('error')}}
	</div>
@endif

@if(Session::has('success'))
	<div class="alert alert-success alert-dismissible" role="alert">
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
		{{@Session::get('success')}}
	</div>
@endif

resources/views/layouts/partials/logout.blade.php
<li>
    <a href="{{ url('/logout') }}"
        onclick="event.preventDefault();
                 document.getElementById('logout-form').submit();">
        Logout
    </a>
    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
        {{ csrf_field() }}
        <button type="submit" v-if="false">Logout</button>
    </form>
</li>

resources/views/layouts/partials/navigation.blade.php
<nav class="navbar navbar-default navbar-static-top navbar-inverse">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    RMF
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ url('/home') }}">Home</a></li>
                </ul>
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('topic.index') }}">Community</a></li>
                </ul>

                <ul class="nav navbar-nav">
                    <li><a href="{{ route('log-viewer::dashboard') }}">Logs</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li>
                            <!-- <dropdown> -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                    <span id="navbar-username">{{ Auth::user()->display_name }}</span> <span class="caret"></span>
                                </a>

                                <ul class="dropdown-menu" role="menu">
                                    @include('layouts.partials.logout')
                                    <li><a href="{{ route('auth.social.connect') }}">Connect accounts</a></li>
                                </ul>
                            <!-- </dropdown> -->
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>