routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('test', function(){
	\Artisan::call('help');
	return 'hello world';
});

Route::get('/', function () {
    return view('welcome');
});

Route::auth();

Route::get('/home', ['uses' => 'HomeController@index', 'as' => 'home']);

Route::group(['prefix' => 'community'], function(){
	Route::resource('topic', 'TopicController');
	Route::resource('post', 'PostController');

	Route::post('topic/{topic}', ['uses' => 'TopicController@reply', 'as'=>'community.topic.reply']);
	Route::post('topic/{topic}', ['uses' => 'TopicController@bump', 'as'=>'community.topic.bump']);

	Route::get('/', 'TopicController@index');



});

Route::get('verify/email/{code}', ['as' => 'email.confirm', 'uses' => 'EmailController@confirm']);


Route::group(['prefix' => 'auth', 'namespace' => 'Auth'], function(){
	Route::get('alternate', ['uses' => 'LoginController@getAlternate']);
	Route::post('alternate', ['uses' => 'LoginController@postAlternate']);

	Route::get('2fa/setup', ['uses'=>'TwoStepController@setup']);
	Route::post('2fa/setup', ['uses'=>'TwoStepController@checkSetup']);
	Route::get('2fa', ['uses'=>'TwoStepController@show']);
	Route::post('2fa', ['uses'=>'TwoStepController@check']);

	Route::get('magic/{user?}', ['as' => 'auth.magic.send', 'uses' => 'LoginController@sendMagicLink']);
	Route::get('magic/{user}/{code}', ['as' => 'auth.magic.check', 'uses' => 'LoginController@checkMagicLink']);

	Route::get('oauth', function(){
		return view('auth.oauth');
	})->middleware('auth');
});

Route::resource('user', 'UserController');
Route::get('profile', function(){
	return redirect()->route('user.show', Auth::user()->slug());
})->middleware('auth');

app/Models/Topic.php
<?php

namespace RMF\Models;

use RMoore\ChangeRecorder\RecordsChanges;
use Illuminate\Database\Eloquent\SoftDeletes;
use Carbon\Carbon;

use RMF\Traits\Slugable;
use Auth;

class Topic extends Model
{
    use RecordsChanges, SoftDeletes, Slugable;

    protected $fillable = ['section_id', 'title', 'author_id'];

    protected $dates = ['deleted_at', 'bumped_at', 'changed_at'];

    public function posts(){
    	return $this->hasMany(Post::class)->orderBy('created_at');
    }

    public function slugEnd(){
        return $this->title;
    }

    public function lastReadAt(){
        $r = $this->views->where('pivot.user_id', 1)->sortByDesc('pivot.created_at')->first();
        return $r ?  $r->pivot['created_at'] : $this->created_at->subDay();
    }

    public function hasBeenRead(){
        return $this->lastReadAt()->gt($this->changed_at);
    }

    public function views(){
        return $this->belongsToMany(User::class, 'topic_views')->withTimestamps();
    }

    public function viewCount(){
        return $this->view_count;
    }

    public function lastPoster(){
        return $this->posts->last()->author;
    }

    public function reply($args){
    	$post = new Post;
    	$post->topic_id = $this->id;
    	$post->author_id = \Auth::id() ?? 0;
    	$post->content = $args['content'];
    	$post->save();

        $this->bumped_at = Carbon::now();
        $this->save();

    	return $post;
    }

    public function touchChanged(){
        $this->changed_at = $this->freshTimestamp();
        $this->save();
    }
}

app/Http/Controllers/TopicController.php
<?php

namespace RMF\Http\Controllers;

use Illuminate\Http\Request;

use RMF\Http\Requests;

use RMF\Models\Topic;

use Auth;

use Carbon\Carbon;

class TopicController extends Controller
{
    public function __construct(){
        $this->middleware('auth', ['except' => ['index', 'show']]);
        $this->middleware('slug:topic');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $topics = Topic::latest('bumped_at')->with('posts', 'posts.author', 'posts.author.ranks', 'views')->get();
        return view('topic.list')->withTopics($topics)->with('useJS', false);//! $request->exists('nojs'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('topic.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $topic = new Topic;
        // $topic->user_id = Auth::id();
        $topic->title = $request->input('title');
        $topic->save();

        $topic->reply(['content' => $request->input('content')]);

        return redirect()->route('topic.show', ['topic' => $topic->slug()]);
    }

    /**
     * Display the specified resource.
     *
     * @param  string  $slug
     * @return \Illuminate\Http\Response
     */
    public function show($slug, Request $request)
    {
        $topic = Topic::fromSlug($slug)->with('posts', 'posts.author')->firstOrFail();
        $topic->increment('view_count');
        // if(Auth::check())
            $topic->views()->attach(Auth::id()?:0);
        
        return view('topic.show')->withTopic($topic)->with('useJS', $request->exists('nojs'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function reply($slug, Request $request){
        $topic = Topic::findFromSlug($slug);

        $topic->reply($request->all());

        return redirect()->route('topic.show', ['topic' => $topic->slug()]);
    }

    public function bump($slug){
        $topic = Topic::findFromSlug($slug);
        $topic->bumped_at = Carbon::now();
        $topic->save();
        return redirect()->back()->with('success', "bumped '$topic->title'");
    }
}

app/Http/Controllers/api/v1/TopicController.php
<?php

namespace RMF\Http\Controllers\api\v1;

use Illuminate\Http\Request;

use RMF\Http\Requests;
use RMF\Http\Controllers\api\ApiController;

use RMF\Models\Topic;

class TopicController extends ApiController
{
    public function __construct(){
        $this->middleware('slug:topic');
        $this->middleware('auth:api', ['except' => ['index', 'show']]);
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return $this->formatCollection(Topic::all());
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/topic/create.blade.php
@extends('layouts.app')
@section('content')

<div class="container">

<form method="post" action="{{ route('community.topic.store') }}" class="form">
	{{ csrf_field() }}

	<div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
        <label for="title" class="col-md-4 control-label">Title</label>

        <div class="col-md-6">
            <input id="title" type="text" class="form-control" name="title" value="{{ old('title') }}">

            @if ($errors->has('title'))
                <span class="help-block">
                    <strong>{{ $errors->first('title') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group{{ $errors->has('content') ? ' has-error' : '' }}">
        <label for="content" class="col-md-4 control-label">Content</label>

        <div class="col-md-6">
            <textarea id="content" type="textarea" rows="10" class="form-control" name="content" value="{{ old('content') }}" v-ckeditor></textarea>

            @if ($errors->has('content'))
                <span class="help-block">
                    <strong>{{ $errors->first('content') }}</strong>
                </span>
            @endif
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-6 col-md-offset-4">
            <button type="submit" class="btn btn-primary">
                Submit
            </button>
        </div>
    </div>
	

</form>



</div>


@endsection

resources/views/topic/list.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
	<div class="well">
		<ul style="padding:0px;">
			@foreach($topics as $topic)
				@if($topic->posts->count() > 0)					
					<li class="topic-list__link">
						<div class="read-circle {{ $topic->hasBeenRead() ? 'read' : 'unread'}}"></div>

						<div class="topic-list__title">
							<a href="{{ route('topic.show', ['topic' => $topic->slug()]) }}" class="block">
								{{ $topic->title }}										
							</a>

							<span>Posted {{ $topic->created_at->diffForHumans() }}</span>
						</div>

						<div class="topic-list__stats">
							<span>
								{{ $topic->posts->count() - 1 }} {{ $topic->posts->count() == 2 ? 'Reply' : 'Replies'}}
							</span>

							<span>
								{{ $topic->viewCount() }} Views
							</span>
						</div>

						<div class="topic-list__last-poster">
							<img src="{{ $topic->lastPoster()->avatar() }}" 
								style="display: inline-table;" height="50" width="50"
							>

							<div class="topic-list__last-poster__info">
								<a 
									class="block display-name display-name__{{ $topic->lastPoster()->rank() }}" 
									style="text-align:left;" 
									href="{{ route('user.show', ['user' => $topic->lastPoster()->slug()]) }}"
								>
									<sized-text :width="150" :max-size="1">{{ $topic->lastPoster()->name() }}</sized-text>
								</a>
								<span>
									{{ $topic->posts->last()->created_at->diffForHumans() }}
								</span>
							</div>
						</div>
					</li>
				@endif
			@endforeach
		</ul>
	</div>
</div>


@endsection

resources/views/topic/show.blade.php
@extends('layouts.app')
@section('content')

<div class="container">
<div class="thread-title-well">
<h1 class="thread-title">{{ $topic->title }}</h1>
</div>
<br>
<div class="post-list-well">
	<div class="topic-reply-count">
		<div>
			<span>This topic has been viewed {{ $topic->viewCount() }} {{ $topic->viewCount() == 1 ? 'time' : 'times' }} and has {{ $topic->posts->count() - 1 }} replies.</span>
		</div>
		<div>
			@if(Auth::id() == $topic->posts->first()->author_id)
				<form class="form-horizontal post-action-button" action="{{route('community.topic.bump', ['topic'=>$topic->slug()]) }}" method="post">
					{{ csrf_field() }}
					<button class="btn btn-default btn-sm btn__bump">Bump</button>
				</form>
			@endif
		</div>
		
	</div>
	<div class="">
		@foreach($topic->posts as $post)
			@if($useJS)	
				@include('post.view')
			@else		
				@include('post.nojs')			
			@endif
		@endforeach
	</div>
	@if(Auth::check())
		<br>
		@include('topic.partials.reply')
	@endif

</div>
</div>

@endsection